# Generated by Django 4.2.20 on 2025-03-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cycle_hours',
            field=models.FloatField(default=70.0),
        ),
    ]
